on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Hexo-build:
    name: Hexo blog build
    runs-on: ubuntu-latest

    steps:
      - name: Get files from repository
        uses: actions/checkout@v4
      
      - name: Install pandoc
        run: |
          version=$(echo "$(curl -s https://api.github.com/repos/jgm/pandoc/releases/latest)" | grep 'tag_name' | cut -d'"' -f4)
          wget -c https://github.com/jgm/pandoc/releases/download/$version/pandoc-$version-1-amd64.deb
          sudo dpkg -i pandoc-$version-1-amd64.deb
          echo "--------------------------------------------------------------------------------"
          pandoc -v
          echo "--------------------------------------------------------------------------------"
        shell: bash
      
      - name: Insatll hexo
        run: |
          echo "--------------------------------------------------"
          cd ${{ github.workspace }}
          echo "pandoc version: $(pandoc -v)"
          echo "nodejs version: $(node -v)"
          echo "npm version: $(npm -v)"
          npm install -g hexo-cli
          echo "--------------------------------------------------"
        shell: bash
      
      - name: Init blog & install redefine theme
        run: |
          cd ${{ github.workspace }}
          hexo init blog
          cd blog
          git clone https://github.com/EvanNotFound/hexo-theme-redefine.git themes/redefine
        shell: bash
        
      - name: Insatll npm packages
        run: |
          cd ${{ github.workspace }}/blog
          npm install js-yaml
          npm install hexo-all-minifier
          npm uninstall hexo-blog-encrypt
          npm install hexo-filter-mermaid-diagrams
          npm install hexo-filter-mathjax
          npm uninstall hexo-renderer-marked
          npm install hexo-renderer-pandoc
        shell: bash
        
      - name: Copy files
        run: |
          cd ${{ github.workspace }}
          cp ./Redefine/lunar.js ./blog/
          cp ./Redefine/*.yml ./blog/
          cp -r ./Redefine/source/ ./blog/
          cp -r ./Redefine/scaffolds ./blog/
        shell: bash

      - name: Generat blog
        run: |
          cd ${{ github.workspace }}/blog
          node ./lunar.js
          hexo g
        shell: bash
        
      - name: Add README file & Compress files
        run: |
          cd ${{ github.workspace }}/blog
          cp ../Redefine/source/.README.md ./public/README.md
          tar -zcvf public.tar.gz ./public 
        shell: bash
          
      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GH_PAT }}
          branch: main
          folder: blog/public
          git-config-name: ${{ github.actor }}
          git-config-email: ${{ secrets.GIT_EMAIL }}
          repository-name: Zhang-Yirui/Zhang-Yirui.github.io
       
      - name: SSH Server1 Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.SERVER1_HOST }}
          port: ${{ secrets.SERVER1_PORT }}
          username: ${{ secrets.SERVER1_USERNAME }}
          private_key: ${{ secrets.SERVER1_PRIVATE_KEY }}
          scp_source: ${{ github.workspace }}/blog/public.tar.gz
          scp_target: /www/wwwroot/blog.redefine
          before_script: |
            rm -f /www/wwwroot/blog.redefine/public.tar.gz
            rm -f /www/wwwroot/blog.redefine/nohup.log
          after_script: |
            nohup tar -xzvf /www/wwwroot/blog.redefine/public.tar.gz -C /www/wwwroot/blog.redefine/ > /www/wwwroot/blog.redefine/nohup.log 2>&1 &
      
      - name: SSH Server2 Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.SERVER2_HOST }}
          port: ${{ secrets.SERVER2_PORT }}
          username: ${{ secrets.SERVER2_USERNAME }}
          private_key: ${{ secrets.SERVER2_PRIVATE_KEY }}
          scp_source: ${{ github.workspace }}/blog/public.tar.gz
          scp_target: /www/wwwroot/blog.redefine
          before_script: |
            rm -f /www/Redefine/public.tar.gz
            rm -f /www/Redefine/nohup.log
          after_script: |
            nohup tar -xzvf /www/Redefine/public.tar.gz -C /www/Redefine/ > /www/Redefine/nohup.log 2>&1 &
